// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'device_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$DeviceInfoImpl _$$DeviceInfoImplFromJson(Map<String, dynamic> json) =>
    _$DeviceInfoImpl(
      model: json['model'] as String,
      brand: json['brand'] as String,
      manufacturer: json['manufacturer'] as String,
      serialNo: json['serialNo'] as String,
      device: json['device'] as String,
      productName: json['productName'] as String,
      releaseVersion: json['releaseVersion'] as String,
      sdkVersion: json['sdkVersion'] as String,
      fingerprint: json['fingerprint'] as String,
      androidId: json['androidId'] as String,
      imei: json['imei'] as String,
      subscriberId: json['subscriberId'] as String,
      advertisingId: json['advertisingId'] as String,
      ssid: json['ssid'] as String?,
      macAddress: json['macAddress'] as String?,
      height: (json['height'] as num?)?.toInt(),
      width: (json['width'] as num?)?.toInt(),
      androidSerial: json['androidSerial'] as String,
      phoneNumber: json['phoneNumber'] as String,
      glVendor: json['glVendor'] as String,
      glRender: json['glRender'] as String,
      hardware: json['hardware'] as String,
      id: json['id'] as String,
      host: json['host'] as String,
      radio: json['radio'] as String,
      bootloader: json['bootloader'] as String,
      display: json['display'] as String,
      board: json['board'] as String,
      codename: json['codename'] as String,
      serialSimNumber: json['serialSimNumber'] as String,
      bssid: json['bssid'] as String,
      operator: json['operator'] as String,
      operatorName: json['operatorName'] as String,
      countryIso: json['countryIso'] as String,
      userAgent: json['userAgent'] as String,
      osVersion: json['osVersion'] as String,
      macHardware: json['macHardware'] as String,
      wifiIp: json['wifiIp'] as String,
      versionChrome: json['versionChrome'] as String,
    );

Map<String, dynamic> _$$DeviceInfoImplToJson(_$DeviceInfoImpl instance) =>
    <String, dynamic>{
      'model': instance.model,
      'brand': instance.brand,
      'manufacturer': instance.manufacturer,
      'serialNo': instance.serialNo,
      'device': instance.device,
      'productName': instance.productName,
      'releaseVersion': instance.releaseVersion,
      'sdkVersion': instance.sdkVersion,
      'fingerprint': instance.fingerprint,
      'androidId': instance.androidId,
      'imei': instance.imei,
      'subscriberId': instance.subscriberId,
      'advertisingId': instance.advertisingId,
      'ssid': instance.ssid,
      'macAddress': instance.macAddress,
      'height': instance.height,
      'width': instance.width,
      'androidSerial': instance.androidSerial,
      'phoneNumber': instance.phoneNumber,
      'glVendor': instance.glVendor,
      'glRender': instance.glRender,
      'hardware': instance.hardware,
      'id': instance.id,
      'host': instance.host,
      'radio': instance.radio,
      'bootloader': instance.bootloader,
      'display': instance.display,
      'board': instance.board,
      'codename': instance.codename,
      'serialSimNumber': instance.serialSimNumber,
      'bssid': instance.bssid,
      'operator': instance.operator,
      'operatorName': instance.operatorName,
      'countryIso': instance.countryIso,
      'userAgent': instance.userAgent,
      'osVersion': instance.osVersion,
      'macHardware': instance.macHardware,
      'wifiIp': instance.wifiIp,
      'versionChrome': instance.versionChrome,
    };
