import 'package:freezed_annotation/freezed_annotation.dart';

part 'device_info.freezed.dart';
part 'device_info.g.dart';

@freezed
class DeviceInfo with _$DeviceInfo {
  factory DeviceInfo({
    required String model,
    required String brand,
    required String manufacturer,
    required String device,
    required String productName,
    required String releaseVersion,
    required String sdkVersion,
    String? fingerprint
  }) = _DeviceInfo;

  factory DeviceInfo.fromJson(Map<String, dynamic> json) => _$DeviceInfoFromJson(json);
}

final List<DeviceInfo> deviceInfoList = [
  // Xiaomi Devices
  DeviceInfo(
    model: "Mi A1",
    brand: "xiaomi",
    manufacturer: "xiaomi",
    device: "tissot",
    productName: "tissot_sprout",
    releaseVersion: "8.0.0",
    sdkVersion: "26",
  ),
  DeviceInfo(
    model: "Redmi Note 8",
    brand: "xiaomi",
    manufacturer: "xiaomi",
    device: "ginkgo",
    productName: "ginkgo_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Poco X3 NFC",
    brand: "xiaomi",
    manufacturer: "xiaomi",
    device: "surya",
    productName: "surya_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),

  // Samsung Devices
  DeviceInfo(
    model: "Galaxy S9",
    brand: "samsung",
    manufacturer: "samsung",
    device: "starlte",
    productName: "starltexx",
    releaseVersion: "10",
    sdkVersion: "29",
  ),
  DeviceInfo(
    model: "Galaxy A51",
    brand: "samsung",
    manufacturer: "samsung",
    device: "a51",
    productName: "a51xx",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Galaxy Note 20",
    brand: "samsung",
    manufacturer: "samsung",
    device: "c1s",
    productName: "c1sxx",
    releaseVersion: "12",
    sdkVersion: "31",
  ),

  // Google Devices
  DeviceInfo(
    model: "Pixel 4",
    brand: "google",
    manufacturer: "google",
    device: "flame",
    productName: "flame_user",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Pixel 6",
    brand: "google",
    manufacturer: "google",
    device: "oriole",
    productName: "oriole",
    releaseVersion: "13",
    sdkVersion: "33",
  ),
  DeviceInfo(
    model: "Pixel 3a",
    brand: "google",
    manufacturer: "google",
    device: "sargo",
    productName: "sargo",
    releaseVersion: "10",
    sdkVersion: "29",
  ),

  // OnePlus Devices
  DeviceInfo(
    model: "OnePlus 7",
    brand: "oneplus",
    manufacturer: "oneplus",
    device: "oneplus7",
    productName: "oneplus7_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "OnePlus 9",
    brand: "oneplus",
    manufacturer: "oneplus",
    device: "lemonade",
    productName: "lemonade_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
  DeviceInfo(
    model: "OnePlus Nord",
    brand: "oneplus",
    manufacturer: "oneplus",
    device: "avicii",
    productName: "avicii_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),

  // Oppo Devices
  DeviceInfo(
    model: "Oppo Reno 4",
    brand: "oppo",
    manufacturer: "oppo",
    device: "reno4mo",
    productName: "reno4mo",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Oppo Find X3 Pro",
    brand: "oppo",
    manufacturer: "oppo",
    device: "findx3pro",
    productName: "findx3pro",
    releaseVersion: "12",
    sdkVersion: "31",
  ),

  // Vivo Devices
  DeviceInfo(
    model: "Vivo Y70",
    brand: "vivo",
    manufacturer: "vivo",
    device: "y70",
    productName: "y70_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Vivo X60 Pro",
    brand: "vivo",
    manufacturer: "vivo",
    device: "x60pro",
    productName: "x60pro_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),

  // Realme Devices
  DeviceInfo(
    model: "Realme 8",
    brand: "realme",
    manufacturer: "realme",
    device: "RMX3085",
    productName: "RMX3085_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Realme GT Neo",
    brand: "realme",
    manufacturer: "realme",
    device: "RMX3031",
    productName: "RMX3031_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),

  // Additional Devices
  DeviceInfo(
    model: "Huawei P30",
    brand: "huawei",
    manufacturer: "huawei",
    device: "ele",
    productName: "ele-l29",
    releaseVersion: "10",
    sdkVersion: "29",
  ),
  DeviceInfo(
    model: "Moto G Power",
    brand: "motorola",
    manufacturer: "motorola",
    device: "sofia",
    productName: "sofia_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Nokia 7.2",
    brand: "nokia",
    manufacturer: "nokia",
    device: "daredevil",
    productName: "daredevil_global",
    releaseVersion: "10",
    sdkVersion: "29",
  ),
  DeviceInfo(
    model: "Asus Zenfone 8",
    brand: "asus",
    manufacturer: "asus",
    device: "sake",
    productName: "sake_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
  DeviceInfo(
    model: "Sony Xperia 1 III",
    brand: "sony",
    manufacturer: "sony",
    device: "xq-bc72",
    productName: "xq-bc72",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
  DeviceInfo(
    model: "LG Velvet",
    brand: "lg",
    manufacturer: "lg",
    device: "velvet",
    productName: "velvet_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Redmi Note 10 Pro",
    brand: "xiaomi",
    manufacturer: "xiaomi",
    device: "sweet",
    productName: "sweet_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
  DeviceInfo(
    model: "Galaxy M32",
    brand: "samsung",
    manufacturer: "samsung",
    device: "m32",
    productName: "m32xx",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Poco F3",
    brand: "xiaomi",
    manufacturer: "xiaomi",
    device: "alioth",
    productName: "alioth_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
  DeviceInfo(
    model: "Oppo A94",
    brand: "oppo",
    manufacturer: "oppo",
    device: "CPH2203",
    productName: "CPH2203_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Vivo V21",
    brand: "vivo",
    manufacturer: "vivo",
    device: "v2050",
    productName: "v2050_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
  DeviceInfo(
    model: "Realme Narzo 30",
    brand: "realme",
    manufacturer: "realme",
    device: "RMX2156",
    productName: "RMX2156_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "OnePlus 8T",
    brand: "oneplus",
    manufacturer: "oneplus",
    device: "kebab",
    productName: "kebab_global",
    releaseVersion: "11",
    sdkVersion: "30",
  ),
  DeviceInfo(
    model: "Pixel 5",
    brand: "google",
    manufacturer: "google",
    device: "redfin",
    productName: "redfin",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
  DeviceInfo(
    model: "Galaxy Z Flip 3",
    brand: "samsung",
    manufacturer: "samsung",
    device: "bloom",
    productName: "bloomxx",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
  DeviceInfo(
    model: "Mi 11 Lite",
    brand: "xiaomi",
    manufacturer: "xiaomi",
    device: "courbet",
    productName: "courbet_global",
    releaseVersion: "12",
    sdkVersion: "31",
  ),
];